title: chungleboi (Cristian Ortiz)
logo: IMG_7609.jpg
description: Playing catchup and documenting my school and home lab projects.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

# Custom styles
include: ["style.css"]
