title: chungleboi (Cristian Ortiz)
logo: assets/images/IMG_7609-ai-brush-removebg-04b4rfqs.png
description: Playing catchup and documenting my school and home lab projects.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
