title: ChungleBoi's Portfolio
logo: /assets/img/logo.png
description: Playing catchup and documenting my school and home lab projects.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
