title: chungleboi (Cristian Ortiz)
logo: IMG_7609-ai-brush-removebg-04b4rfqs.png
logo: binary-5389555_1920.png
logo: octopus-7762800_1920.png
description: Playing catchup and documenting my school and home lab projects.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
